networks:
  local:
    driver: bridge

services:
  nats:
    image: nats:alpine
    container_name: nats
    restart: always
    command: -c /etc/nats/nats.conf
    ports:
      - "4222:4222"
      - "6222:6222"
      - "8222:8222"
    volumes:
      - ./configs/nats/nats.conf:/etc/nats/nats.conf
    networks:
      - local

  # prometheus:
  #   image: prom/prometheus
  #   container_name: prometheus
  #   restart: always
  #   ports:
  #     - "9090:9090"
  #   volumes:
  #     - ./configs/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
  #   networks:
  #     - local

  # grafana:
  #   image: grafana/grafana
  #   container_name: grafana
  #   restart: always
  #   ports:
  #     - "3000:3000"
  #   networks:
  #     - local
